# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Client2LoginGate.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Client2LoginGate.proto',
  package='',
  serialized_pb='\n\x16\x43lient2LoginGate.proto\"\xca\x01\n\rCreateAccount\x12\n\n\x02ID\x18\x01 \x02(\t\x12\x10\n\x08Password\x18\x02 \x02(\t\x12\x10\n\x08\x42irthday\x18\x03 \x02(\t\x12\x0c\n\x04Name\x18\x04 \x02(\t\x12\x12\n\nIDCardCode\x18\x05 \x02(\t\x12\x11\n\tQuestionA\x18\x06 \x02(\t\x12\x0f\n\x07\x41nswerA\x18\x07 \x02(\t\x12\x11\n\tQuestionB\x18\x08 \x02(\t\x12\x0f\n\x07\x41nswerB\x18\t \x02(\t\x12\x10\n\x08PhoneNum\x18\n \x01(\t\x12\r\n\x05\x45Mail\x18\x0b \x01(\t\"8\n\nCreateRole\x12\x10\n\x08RoleName\x18\x01 \x02(\t\x12\x0b\n\x03Sex\x18\x02 \x02(\x0c\x12\x0b\n\x03Job\x18\x03 \x02(\x0c\"\x98\x01\n\tClientMsg\x12\x1a\n\x04Type\x18\x01 \x02(\x0e\x32\x0c.MessageType\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x10\n\x08Password\x18\x03 \x01(\t\x12\x1f\n\x07\x41\x63\x63ount\x18\x04 \x01(\x0b\x32\x0e.CreateAccount\x12\x13\n\x0bNewPassword\x18\x05 \x01(\t\x12\x1b\n\x06\x43rRole\x18\x06 \x01(\x0b\x32\x0b.CreateRole\"U\n\x08RoleInfo\x12\x0e\n\x06RoleID\x18\x01 \x02(\x05\x12\x10\n\x08RoleName\x18\x02 \x02(\t\x12\x0b\n\x03Sex\x18\x03 \x02(\x0c\x12\x0b\n\x03Job\x18\x04 \x02(\x0c\x12\r\n\x05Level\x18\x05 \x02(\x05\"u\n\x0cLoginGateMsg\x12\x1a\n\x04Type\x18\x01 \x02(\x0e\x32\x0c.MessageType\x12\x1c\n\x05State\x18\x02 \x02(\x0e\x32\r.RespondState\x12\x0e\n\x06Reason\x18\x03 \x01(\t\x12\x1b\n\x08RoleList\x18\x04 \x03(\x0b\x32\t.RoleInfo*\x95\x01\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x43HECKACCOUNT\x10\x01\x12\x13\n\x0f\x43HANAGEPASSWORD\x10\x02\x12\x14\n\x10\x43REATENEWACCOUNT\x10\x03\x12\x0b\n\x07GETROLE\x10\x04\x12\x11\n\rCREATENEWROLE\x10\x05\x12\x0b\n\x07\x44\x45LROLE\x10\x06\x12\x0f\n\x0bGETGAMEGATE\x10\x07*>\n\x0cRespondState\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x12\n\n\x06UNKNOW\x10\x04')

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECKACCOUNT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHANAGEPASSWORD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATENEWACCOUNT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GETROLE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATENEWROLE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELROLE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GETGAMEGATE', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=651,
  serialized_end=800,
)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_RESPONDSTATE = _descriptor.EnumDescriptor(
  name='RespondState',
  full_name='RespondState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOW', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=802,
  serialized_end=864,
)

RespondState = enum_type_wrapper.EnumTypeWrapper(_RESPONDSTATE)
UNKNOWN = 0
CHECKACCOUNT = 1
CHANAGEPASSWORD = 2
CREATENEWACCOUNT = 3
GETROLE = 4
CREATENEWROLE = 5
DELROLE = 6
GETGAMEGATE = 7
SUCCESS = 1
FAILED = 2
ERROR = 3
UNKNOW = 4



_CREATEACCOUNT = _descriptor.Descriptor(
  name='CreateAccount',
  full_name='CreateAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='CreateAccount.ID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Password', full_name='CreateAccount.Password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Birthday', full_name='CreateAccount.Birthday', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Name', full_name='CreateAccount.Name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IDCardCode', full_name='CreateAccount.IDCardCode', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QuestionA', full_name='CreateAccount.QuestionA', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AnswerA', full_name='CreateAccount.AnswerA', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='QuestionB', full_name='CreateAccount.QuestionB', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AnswerB', full_name='CreateAccount.AnswerB', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PhoneNum', full_name='CreateAccount.PhoneNum', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EMail', full_name='CreateAccount.EMail', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=229,
)


_CREATEROLE = _descriptor.Descriptor(
  name='CreateRole',
  full_name='CreateRole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoleName', full_name='CreateRole.RoleName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sex', full_name='CreateRole.Sex', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Job', full_name='CreateRole.Job', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=231,
  serialized_end=287,
)


_CLIENTMSG = _descriptor.Descriptor(
  name='ClientMsg',
  full_name='ClientMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='ClientMsg.Type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ID', full_name='ClientMsg.ID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Password', full_name='ClientMsg.Password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Account', full_name='ClientMsg.Account', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NewPassword', full_name='ClientMsg.NewPassword', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CrRole', full_name='ClientMsg.CrRole', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=442,
)


_ROLEINFO = _descriptor.Descriptor(
  name='RoleInfo',
  full_name='RoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoleID', full_name='RoleInfo.RoleID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RoleName', full_name='RoleInfo.RoleName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sex', full_name='RoleInfo.Sex', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Job', full_name='RoleInfo.Job', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Level', full_name='RoleInfo.Level', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=444,
  serialized_end=529,
)


_LOGINGATEMSG = _descriptor.Descriptor(
  name='LoginGateMsg',
  full_name='LoginGateMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='LoginGateMsg.Type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='State', full_name='LoginGateMsg.State', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Reason', full_name='LoginGateMsg.Reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RoleList', full_name='LoginGateMsg.RoleList', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=531,
  serialized_end=648,
)

_CLIENTMSG.fields_by_name['Type'].enum_type = _MESSAGETYPE
_CLIENTMSG.fields_by_name['Account'].message_type = _CREATEACCOUNT
_CLIENTMSG.fields_by_name['CrRole'].message_type = _CREATEROLE
_LOGINGATEMSG.fields_by_name['Type'].enum_type = _MESSAGETYPE
_LOGINGATEMSG.fields_by_name['State'].enum_type = _RESPONDSTATE
_LOGINGATEMSG.fields_by_name['RoleList'].message_type = _ROLEINFO
DESCRIPTOR.message_types_by_name['CreateAccount'] = _CREATEACCOUNT
DESCRIPTOR.message_types_by_name['CreateRole'] = _CREATEROLE
DESCRIPTOR.message_types_by_name['ClientMsg'] = _CLIENTMSG
DESCRIPTOR.message_types_by_name['RoleInfo'] = _ROLEINFO
DESCRIPTOR.message_types_by_name['LoginGateMsg'] = _LOGINGATEMSG

class CreateAccount(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEACCOUNT

  # @@protoc_insertion_point(class_scope:CreateAccount)

class CreateRole(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATEROLE

  # @@protoc_insertion_point(class_scope:CreateRole)

class ClientMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTMSG

  # @@protoc_insertion_point(class_scope:ClientMsg)

class RoleInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ROLEINFO

  # @@protoc_insertion_point(class_scope:RoleInfo)

class LoginGateMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINGATEMSG

  # @@protoc_insertion_point(class_scope:LoginGateMsg)


# @@protoc_insertion_point(module_scope)
